# ===================================================================
# Spring Boot configuration for the "staging" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: INFO
    tech.jhipster: INFO
    com.tyse.scrutiny.gateway: DEBUG

management:
  health:
    mail:
      enabled: true

spring:
  cloud:
    consul:
      config:
        fail-fast: true
        format: yaml
        profile-separator: '-'
      discovery:
        prefer-ip-address: true
        tags:
          - profile=${spring.profiles.active}
          - version='@project.version@'
          - git-version=${git.commit.id.describe:}
          - git-commit=${git.commit.id.abbrev:}
          - git-branch=${git.branch:}
      host: consul
      port: 8500
  mail:
    host: mailhog
    port: 1025
    username:
    password:
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  messages:
    cache-duration: PT10S # 10 seconds

server:
  port: 8080
  # make sure requests the proxy uri instead of the server one
  forward-headers-strategy: native

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  gateway:
    rate-limiting:
      enabled: true
      limit: 100000
      duration-in-seconds: 3600
  mail: # specific JHipster mail property, for standard properties see MailProperties
    base-url: http://192.168.0.58:8090
  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512
