export enum AuditAction {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  DELETED = 'DELETED',
  ACTIVATED = 'ACTIVATED',
  DEACTIVATED = 'DEACTIVATED',
  PERMISSIONS_ADDED = 'PERMISSIONS_ADDED',
  PERMISSIONS_REMOVED = 'PERMISSIONS_REMOVED',
  HIERARCHY_CHANGED = 'HIERARCHY_CHANGED',
}
